export const internetLayers = [
  {
    id: 'cognition',
    index: '00',
    name: 'COGNITIVE FIELD',
    short: 'REASONING',
    radius: 9.4,
    angle: 0.42,
    tilt: -0.05,
    color: 0x87a7ff,
    input: 'USER + MODEL THOUGHT',
    output: 'EXPLICIT PROPOSAL',
    trust: 'Ideas are free to move. No execution authority exists here.',
    route: 'cognitive://proposal/untrusted',
    authority: '0 / NONE',
    proof: ['context hash', 'model trace'],
  },
  {
    id: 'identity',
    index: '01',
    name: 'IDENTITY LAYER',
    short: 'PROVENANCE',
    radius: 11.8,
    angle: 1.55,
    tilt: 0.06,
    color: 0x63e3d2,
    input: 'PRINCIPAL + AGENT + SESSION',
    output: 'BOUND ORIGIN',
    trust: 'The proposal gains a verifiable origin without gaining permission to act.',
    route: 'identity://principal/agent/session',
    authority: '0 / NONE',
    proof: ['principal signature', 'session binding'],
  },
  {
    id: 'intent',
    index: '02',
    name: 'INTENT LAYER',
    short: 'SEMANTICS',
    radius: 14.3,
    angle: 2.72,
    tilt: -0.07,
    color: 0xd7ec72,
    input: 'AMBIGUOUS REQUEST',
    output: 'CANONICAL INTENT',
    trust: 'Natural language is compiled into explicit target, effect, reason, and constraints.',
    route: 'intent://canonical/consequence-bundle',
    authority: '0 / NONE',
    proof: ['semantic digest', 'constraint set'],
  },
  {
    id: 'authority',
    index: '03',
    name: 'AUTHORITY GATE',
    short: 'CAPABILITY',
    radius: 17.0,
    angle: 3.9,
    tilt: 0.08,
    color: 0xffb45f,
    input: 'CANONICAL INTENT + POLICY',
    output: 'BOUNDED CAPABILITY',
    trust: 'Only policy-approved scope, value, target, and lifetime can cross this boundary.',
    route: 'authority://policy/bounded-capability',
    authority: 'BOUNDED / EXPLICIT',
    proof: ['policy decision', 'capability receipt'],
  },
  {
    id: 'consequence',
    index: '04',
    name: 'CONSEQUENCE ORBIT',
    short: 'EXECUTION',
    radius: 19.8,
    angle: 5.06,
    tilt: -0.06,
    color: 0xff736b,
    input: 'BOUNDED CAPABILITY',
    output: 'REAL-WORLD EFFECT',
    trust: 'Execution is narrow, observable, and tied to the exact consequence that was approved.',
    route: 'consequence://target/effect/instance',
    authority: 'CONSUMED ON USE',
    proof: ['external readback', 'independent evidence'],
  },
  {
    id: 'evidence',
    index: '05',
    name: 'EVIDENCE RETURN',
    short: 'PROOF',
    radius: 22.6,
    angle: 6.0,
    tilt: 0.07,
    color: 0xb68cff,
    input: 'OBSERVED OUTCOME',
    output: 'VERIFIABLE REALITY',
    trust: 'The internet receives evidence of what actually happened, closing the loop back to cognition.',
    route: 'proof://consequence/readback',
    authority: '0 / OBSERVATION ONLY',
    proof: ['signed observation', 'reconciliation record'],
  },
]

export const cosmicWorld = {
  name: 'NEXUS-7',
  eyebrow: 'CIEAV / CONNECTED INTERNET MODEL',
  title: 'The internet becomes a world you can enter.',
  copy: 'Pilot the probe across six trust orbits. Each ring turns an untrusted idea into identity, canonical intent, bounded authority, consequence, and proof.',
  rule: 'NO HUMAN AVATARS · NO CITY METAPHOR',
}
